name: Publish to GitHub Package Registry

on: [push]

jobs:
  deploy:
     runs-on: [self-hosted, windowns]
     steps:
     - uses: actions/checkout@v1
     - name: Test docker
       run: docker ps -a