name: Publish to GitHub Package Registry

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Test docker
      uses: 'ssh DELL@192.168.68.107'
      with:
        password: '123'
